config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'expense_types/new'
  get 'expense_types/create'
  get 'expense_types/index'
  get 'expense_types/show'
  get 'expense_types/edit'
  get 'expense_types/update'
  get 'expense_types/delete'
  get 'expense_types/destroy'
  get 'users/edit'
  get 'users/new'
  get 'users/create'
  get 'users/destroy'
  get 'help/index'
  resources :members
  resources :receipts
  resources :expense_types

  root 'receipts#new'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
end

app/models/admin 2.rb
# frozen_string_literal: true

class Admin < ApplicationRecord # rubocop:todo Style/Documentation
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@gmail.com || @tamu.edu\z/

    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord # rubocop:todo Style/Documentation
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@gmail.com || @tamu.edu\z/

    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base # rubocop:todo Style/Documentation
  self.abstract_class = true
end

app/models/expenditure 4.rb
class Expenditure < ApplicationRecord
end

app/models/expenditure.rb
# frozen_string_literal: true

class Expenditure < ApplicationRecord
end

app/models/expense_type.rb
# frozen_string_literal: true

class ExpenseType < ApplicationRecord
  validates :etype, presence: true
  validates :description, presence: true
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
end

app/models/receipt 3.rb
class Receipt < ApplicationRecord
  has_one_attached :picture
end

app/models/receipt.rb
# frozen_string_literal: true

class Receipt < ApplicationRecord
  has_one_attached :picture
  validates :picture, presence: true
  validates :reason, presence: true
  validates :amount, presence: true
  validates :date, presence: true
  validates :status, presence: true
  validates :expense_type, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

app/controllers/expense_types_controller.rb
# frozen_string_literal: true

class ExpenseTypesController < ApplicationController # rubocop:todo Style/Documentation
  before_action :set_expense_type, only: %i[show edit update destroy]

  def index
    @expense_types = ExpenseType.all
  end

  def show; end

  def new
    @expense_type = ExpenseType.new
  end

  def create
    @expense_type = ExpenseType.new(expense_type_params)

    respond_to do |format|
      if @expense_type.save
        format.html { redirect_to @expense_type, notice: 'Expense Type was successfully created.' }
        format.json { render :show, status: :created, location: @expense_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @expense_type.update(expense_type_params)
        format.html { redirect_to @expense_type, notice: 'Expense Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete; end

  def destroy
    @expense_type.destroy
    respond_to do |format|
      format.html { redirect_to expense_types_index_path, notice: 'Expense Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_expense_type
    @expense_type = ExpenseType.find(params[:id])
  end

  def expense_type_params
    params.require(:expense_type).permit(:etype, :description)
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
    def index; end

    def show; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController # rubocop:todo Style/Documentation
  def edit; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @subject.save
      redirect_to(receipts_path)
    else
      render('new')
    end
  end

  def destroy; end
end

app/helpers/application_helper 2.rb
module ApplicationHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper # rubocop:todo Style/Documentation
end

app/helpers/expense_type_helper.rb
# frozen_string_literal: true

module ExpenseTypeHelper # rubocop:todo Style/Documentation
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/helpers/receipts_helper 2.rb
# frozen_string_literal: true

module ReceiptsHelper # rubocop:todo Style/Documentation
end

app/helpers/receipts_helper 3.rb
module ReceiptsHelper
end

app/helpers/receipts_helper.rb
# frozen_string_literal: true

module ReceiptsHelper # rubocop:todo Style/Documentation
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper # rubocop:todo Style/Documentation
end

app/views/expense_type/new.html.erb
<h1>New Expense Type</h1>

<%= render 'form', expense_type: @expense_type %>

<%= link_to 'Back', expense_type_index_path %>

app/views/expense_types/_form.html.erb
<% if $user_role == "Admin" %>

<%= form_with(model: expense_type) do |form| %>

  <div class="field">
    <%= form.label :etype, "Expense Type" %>
    <%= form.text_field :etype %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<% end %>

app/views/expense_types/create.html.erb
<h1>ExpenseType#create</h1>
<p>Find me in app/views/expense_type/create.html.erb</p>

app/views/expense_types/edit.html.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<style>
  .show-back {
    margin-left: 200px;
  }
</style>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a class="active" href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>
<% if $user_role == "Admin" %>

<div class="section-title">
  <h1>Editing Expense Type</h1>
</div>

<%= render 'form', expense_type: @expense_type %>

<div class="show-back">
    <%= link_to 'Show', @expense_type %> |
    <%= link_to 'Back', expense_type_path %>
</div>

<body>
    <center>
      <div class="logo">
        <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
      </div>
    </center
</body> 

<% end %>

app/views/expense_types/index.html.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a class="active" href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>


<style>
table, th, td {
  border: 1px solid black;
  margin-left: 200px;
}
th, td {
  padding-top: 10px;
  padding-bottom: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
.newET {
  margin-left: 200px;
}
</style>

<% if $user_role == "Admin" %>

<p id="notice"><%= notice %></p>

<div class="section-title">
  <h1>Expense Types</h1>
</div>

<div class="newET">
  <%= button_to 'New Expense Type', expense_types_new_path, method: :get %>
</div>

<br>

<table>
  <thead>
    <tr>
      <th>Expense Type</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @expense_types.each do |expense_type| %>
      <tr>
        <td><%= expense_type.etype %></td>
        <td><%= expense_type.description %></td>
        <td><%= link_to 'Show', expense_type %></td>
        <td><%= link_to 'Edit', edit_expense_type_path(expense_type) %></td>
        <td><%= link_to 'Delete', expense_type, method: :delete, data: { confirm: 'Are you sure you want to delete this expense type?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<body>
  <center>
    <div class="logo">
      <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
    </div>
  </center
</body>

<% end %>

app/views/expense_types/new.html.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<style>
.back {
    margin-left: 200px;
}
</style>


<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a class="active" href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>

<% if $user_role == "Admin" %>

<div class="section-title">
  <h1>New Expense Type</h1>
</div>

<%= render 'form', expense_type: @expense_type %>

<div class="back">
    <%= link_to 'Back', expense_types_index_path %>
</div> 

<body>
    <center>
      <div class="logo">
        <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
      </div>
    </center
</body> 

<% end %>

app/views/expense_types/show.html.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<style>
  p {
    margin-left: 200px;
  }
  .edit-back {
    margin-left: 200px;
  }
</style>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a class="active" href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>

<% if $user_role == "Admin" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Expense Type:</strong>
  <%= @expense_type.etype %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expense_type.description %>
</p>

<div class="edit-back">
    <%= link_to 'Edit', edit_expense_type_path(@expense_type) %> |
    <%= link_to 'Back', expense_types_index_path %>
</div>

<body>
    <center>
      <div class="logo">
        <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
      </div>
    </center
</body> 

<% end %>

app/views/expense_types/update.html.erb
<h1>ExpenseType#update</h1>
<p>Find me in app/views/expense_type/update.html.erb</p>