config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'expense_types/new'
  get 'expense_types/create'
  get 'expense_types/index'
  get 'expense_types/show'
  get 'expense_types/edit'
  get 'expense_types/update'
  get 'expense_types/delete'
  get 'expense_types/destroy'
  get 'users/edit'
  get 'users/new'
  get 'users/create'
  get 'users/destroy'
  get 'help/index'
  resources :members
  resources :receipts
  resources :expense_types

  root 'receipts#new'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
end

app/models/receipt.rb
# frozen_string_literal: true

class Receipt < ApplicationRecord
  has_one_attached :picture
  validates :picture, presence: true
  validates :reason, presence: true
  validates :amount, presence: true
  validates :date, presence: true
  validates :status, presence: true
  validates :expense_type, presence: true
end

app/controllers/receipts_controller.rb
# frozen_string_literal: true

class ReceiptsController < ApplicationController # rubocop:todo Style/Documentation
  before_action :set_receipt, only: %i[show edit update destroy]
  @@sort_dir = 1 # desc # rubocop:todo Style/ClassVars

  # GET /receipts or /receipts.json
  # rubocop:todo Metrics/PerceivedComplexity
  # rubocop:todo Metrics/MethodLength
  # rubocop:todo Metrics/AbcSize
  def index # rubocop:todo Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/MethodLength, Metrics/PerceivedComplexity
    @receipts = Receipt.all
    case params[:order]
    when 'date'
      case @@sort_dir
      when 1
        @receipts = Receipt.all.sort_by(&:date)
      when -1
        @receipts = Receipt.all.sort_by(&:date).reverse!
      end
      @@sort_dir *= -1 # rubocop:todo Style/ClassVars
    when 'amount'
      @receipts = Receipt.all.sort_by { |receipt| @@sort_dir * receipt.amount }
      @@sort_dir *= -1 # rubocop:todo Style/ClassVars
    when 'status'
      case @@sort_dir
      when 1
        @receipts = Receipt.all.sort_by(&:status)
      when -1
        @receipts = Receipt.all.sort_by(&:status).reverse!
      end
      @@sort_dir *= -1 # rubocop:todo Style/ClassVars
    end
  end
  # rubocop:enable Metrics/AbcSize
  # rubocop:enable Metrics/MethodLength
  # rubocop:enable Metrics/PerceivedComplexity

  # GET /receipts/1 or /receipts/1.json
  def show; end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
  end

  # GET /receipts/1/edit
  def edit; end

  # POST /receipts or /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1 or /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1 or /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_receipt
    @receipt = Receipt.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def receipt_params
    params.require(:receipt).permit(:picture, :amount, :reason, :date, :status, :expense_type)
  end
end

app/helpers/receipts_helper.rb
# frozen_string_literal: true

module ReceiptsHelper # rubocop:todo Style/Documentation
end

app/views/receipts/_form.html 2.erb
<%= form_with(model: receipt) do |form| %>
  <% if receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
        <% receipt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_field :reason %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :date, "Date of Transaction" %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :status%>
    <%= form.select :status, ['Active', 'Completed'] %>
  </div>

  <div class="field">
    <%= form.label :expense_type%>
    <%= form.collection_select(:expense_type, ExpenseType.all, :etype, :etype, {:prompt => true})%>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/receipts/_form.html 3.erb
<%= form_with(model: receipt) do |form| %>
  <% if receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
        <% receipt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_field :reason %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/receipts/_form.html.erb
<%= form_with(model: receipt) do |form| %>
  <% if receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
        <% receipt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="field">
    <%= form.label :expense_type%>
    <%= form.collection_select(:expense_type, ExpenseType.all, :etype, :etype, {:prompt => true})%>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :date, "Date of Transaction" %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :status%>
    <%= form.select :status, ['Active', 'Completed'] %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :reason %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/receipts/edit.html 2.erb
<h1>Editing Receipt</h1>

<%= render 'form', receipt: @receipt %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/edit.html.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<style>
  .show-back {
    margin-left: 200px;
  }
</style>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a class="active" href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>
<% if $user_role == "Admin" %>

  <div class="section-title">
    <h1>Editing Receipt</h1>
  </div>

    <%= render 'form', receipt: @receipt %>

    <div class="show-back">
      <%= link_to 'Show', @receipt %> |
      <%= link_to 'Back', receipts_path %>
    </div>

    <body>
        <center>
          <div class="logo">
            <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
          </div>
        </center
    </body> 
    
<% end %>

app/views/receipts/index.html 2.erb
<style>
table, th, td {
  border: 1px solid black;
}
th, td {
  padding-top: 10px;
  padding-bottom: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
</style>

<p id="notice"><%= notice %></p>

<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a class="active" href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                <%= $user_name %>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>


<h1>Receipts</h1>

<%= button_to 'New Receipt', new_receipt_path, method: :get %>

<br>

<table>
  <thead>
    <tr>
      <th>Reason</th>
      <th><%= link_to "Amount", receipts_path(order: 'amount') %></th>
      <th><%= link_to "Date of Transaction", receipts_path(order: 'date') %></th>
      <th><%= link_to "Status", receipts_path(order: 'status') %></th>
      <th>Expense Type</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.reason %></td>
        <td>$<%= receipt.amount %></td>
        <td><%= receipt.date %></td>
        <td><%= receipt.status %></td>
        <% if $user_role == "Admin" %>
          <td><%= link_to 'Show', receipt %></td>
          <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
          <td><%= link_to 'Delete', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/receipts/index.html 3.erb
<p id="notice"><%= notice %></p>

<h1>Receipts</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Amount</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.id %></td>
        <td><%= receipt.amount %></td>
        <td><%= receipt.reason %></td>
        <td><%= link_to 'Show', receipt %></td>
        <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
        <td><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/index.html.erb
<style>
table, th, td {
  border: 1px solid black;
  margin-left: 200px;
}
th, td {
  padding-top: 10px;
  padding-bottom: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
.newReceipt {
  margin-left: 200px;
}
</style>

<p id="notice"><%= notice %></p>

<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a class="active" href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                  <% if $user_role == "Admin" %>
                    <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <% end %>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>


<div class="section-title">
  <h1>Receipts</h1>
</div>

<div class="newReceipt">
  <%= button_to 'New Receipt', new_receipt_path, method: :get %>
</div>

<br>

<table>
  <thead>
    <tr>
      <th>Expense Type</th>
      <th><%= link_to "Amount", receipts_path(order: 'amount') %></th>
      <th><%= link_to "Date of Transaction", receipts_path(order: 'date') %></th>
      <th><%= link_to "Status", receipts_path(order: 'status') %></th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.expense_type %></td> 
        <td>$<%= receipt.amount %></td>
        <td><%= receipt.date %></td>
        <td><%= receipt.status %></td>
        <td><%= receipt.reason %></td>
        <% if $user_role == "Admin" %>
          <td><%= link_to 'Show', receipt %></td>
          <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
          <td><%= link_to 'Delete', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<body>
  <center>
    <div class="logo">
      <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo")%>
    </div>
  </center>
</body> 

app/views/receipts/new.html 2.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a class="active" href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                    <%= $user_name %>
                    <div class="signout-link">
                        <%= link_to "Sign Out", destroy_admin_session_path %>
                    </div>
                </ul>
            </div>
        </div>
    </div>

</body>

<h1>New Receipt</h1>

<%= render 'form', receipt: @receipt %>

<!-- <%= link_to 'Back', receipts_path %> -->

app/views/receipts/new.html 3.erb
<h1>New Receipt</h1>

<%= render 'form', receipt: @receipt %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/new.html.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a class="active" href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                    <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                    <div class="signout-link">
                        <%= link_to "Sign Out", destroy_admin_session_path %>
                    </div>
                </ul>
            </div>
        </div>
    </div>

</body>

<div class="section-title">
    <h1>New Receipt</h1>
</div>

<%= render 'form', receipt: @receipt %>

<!-- <%= link_to 'Back', receipts_path %> -->

<body>
    <center>
        <div class="logo">
            <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
        </div>
    </center>
</body> 

app/views/receipts/show.html 2.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <img src="<%= url_for(@receipt.picture) %>"/>
</p>

<p>
  <strong>Amount:</strong>
  <%= @receipt.amount %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @receipt.reason %>
</p>

<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<style>
  p {
    margin-left: 200px;
  }
  .edit-back {
    margin-left: 200px;
  }
</style>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a class="active" href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                  <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>



<p id="notice"><%= notice %></p>

<p>
<img src="<%= url_for(@receipt.picture) %>" width="300" height="400"/>
</p>

<p>
<strong>Expense Type:</strong>
<%= @receipt.expense_type %>
</p>

<p>
<strong>Amount:</strong>
$<%= @receipt.amount %>
</p>

<p>
<strong>Date of Transaction:</strong>
<%= @receipt.date %>
</p>

<p>
<strong>Status:</strong>
<%= @receipt.status %>
</p>

<p>
<strong>Description:</strong>
<%= @receipt.reason %>
</p>


<div class= "edit-back">
  <%= link_to 'Edit', edit_receipt_path(@receipt) %> |
  <%= link_to 'Back', receipts_path %>
</div>

<body>
    <center>
      <div class="logo">
        <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
      </div>
    </center
</body> 