config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'expense_types/new'
  get 'expense_types/create'
  get 'expense_types/index'
  get 'expense_types/show'
  get 'expense_types/edit'
  get 'expense_types/update'
  get 'expense_types/delete'
  get 'expense_types/destroy'
  get 'users/edit'
  get 'users/new'
  get 'users/create'
  get 'users/destroy'
  get 'help/index'
  resources :members
  resources :receipts
  resources :expense_types

  root 'receipts#new'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
end

app/models/admin 2.rb
# frozen_string_literal: true

class Admin < ApplicationRecord # rubocop:todo Style/Documentation
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@gmail.com || @tamu.edu\z/

    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord # rubocop:todo Style/Documentation
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@gmail.com || @tamu.edu\z/

    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base # rubocop:todo Style/Documentation
  self.abstract_class = true
end

app/models/expenditure 4.rb
class Expenditure < ApplicationRecord
end

app/models/expenditure.rb
# frozen_string_literal: true

class Expenditure < ApplicationRecord
end

app/models/expense_type.rb
# frozen_string_literal: true

class ExpenseType < ApplicationRecord
  validates :etype, presence: true
  validates :description, presence: true
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
end

app/models/receipt 3.rb
class Receipt < ApplicationRecord
  has_one_attached :picture
end

app/models/receipt.rb
# frozen_string_literal: true

class Receipt < ApplicationRecord
  has_one_attached :picture
  validates :picture, presence: true
  validates :reason, presence: true
  validates :amount, presence: true
  validates :date, presence: true
  validates :status, presence: true
  validates :expense_type, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
    def index; end

    def show; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController # rubocop:todo Style/Documentation
  def edit; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @subject.save
      redirect_to(receipts_path)
    else
      render('new')
    end
  end

  def destroy; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper # rubocop:todo Style/Documentation
end

app/helpers/expense_type_helper.rb
# frozen_string_literal: true

module ExpenseTypeHelper # rubocop:todo Style/Documentation
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/helpers/receipts_helper 2.rb
# frozen_string_literal: true

module ReceiptsHelper # rubocop:todo Style/Documentation
end

app/helpers/receipts_helper 3.rb
module ReceiptsHelper
end

app/helpers/receipts_helper.rb
# frozen_string_literal: true

module ReceiptsHelper # rubocop:todo Style/Documentation
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper # rubocop:todo Style/Documentation
end

app/views/layouts/_navbar.html.erb
<header>
	<div>
		<nav>
			<li><%= link_to "Receipts", receipts_path, class: 'nav-link' %> <%= link_to "Expense Types", expense_types_show_path, class: 'nav-link' %></li>
		</nav>
	</div>
</header>

app/views/layouts/application.html 2.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BLC-FAST-APP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body>
    <!-- flash is handled in controller
    <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
      <% end -%>
    <% end %>
    -->
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BLC-FAST</title>
    <%= favicon_link_tag 'blc.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body>
    <!-- flash is handled in controller
    <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
      <% end -%>
    <% end %>
    -->
    <%= yield %>
  </body>
</html>