config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'expense_types/new'
  get 'expense_types/create'
  get 'expense_types/index'
  get 'expense_types/show'
  get 'expense_types/edit'
  get 'expense_types/update'
  get 'expense_types/delete'
  get 'expense_types/destroy'
  get 'users/edit'
  get 'users/new'
  get 'users/create'
  get 'users/destroy'
  get 'help/index'
  resources :members
  resources :receipts
  resources :expense_types

  root 'receipts#new'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  before_action :set_member, only: %i[show edit update destroy]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show; end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit; end

  def find_user_role
    # developer backdoor
    if $user_email == "blc.it.tamu@gmail.com"
      $user_role = "Admin"
    # main log in
    else
      @members = Member.all
      @members.each do |member|
        $user_role = member.role if member.email == $user_email
      end
    end
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(:name, :email, :role)
  end
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/views/members/_form.html.erb
<% if $user_role == "Admin" %>
  <%= form_with(model: member) do |form| %>
    <% if member.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

        <ul>
          <% member.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :role %>
      <%= form.select :role, ['Officer', 'Admin'] %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/members/edit.html.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<style>
  .show-back {
    margin-left: 200px;
  }
</style>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a class="active" href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>
<% if $user_role == "Admin" %>

    <div class="section-title">
        <h1>Editing Officer</h1>   
    </div>

    <%= render 'form', member: @member %>

    <div class="show-back">
        <%= link_to 'Show', @member %> |
        <%= link_to 'Back', members_path %>
    </div>

    <body>
        <center>
        <div class="logo">
            <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
        </div>
        </center
    </body> 
<% end %>

app/views/members/index.html.erb
<style>
table, th, td {
  border: 1px solid black;
  margin-left: 200px;
}
th, td {
  padding-top: 10px;
  padding-bottom: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
.newMember {
  margin-left: 200px;
}
</style>

<p id="notice"><%= notice %></p>

<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a class="active" href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>
<% if $user_role == "Admin" %>

<div class="section-title">
  <h1>Officers</h1>
</div>

<div class="newMember">
  <%= button_to 'New Member', new_member_path, method: :get %>
</div>

<br>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>
        <td><%= member.role %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<body>
  <center>
    <div class="logo">
      <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
    </div>
  </center>
</body> 

<% end %>

app/views/members/new.html.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<style>
.back {
    margin-left: 200px;
}
</style>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a class="active" href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>

<% if $user_role == "Admin" %>

    <div class="section-title">
        <h1>New Member</h1>
    </div>

    <%= render 'form', member: @member %>

    <div class="back">
        <%= link_to 'Back', members_path %>
    </div>

    <body>
        <center>
            <div class="logo">
                <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
            </div>
        </center
    </body>     
<% end %>

app/views/members/show.html.erb
<head>
    <title> BLCFAST </title>
    <link rel="shortcut icon" type="image/x-icon" href="pic/iter.ico">
    <meta name="description" content="">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="translate.css">
    <link rel="stylesheet" id="style_sheet" type="text/css" href="style.css">
    <script src="translate.js"></script>
</head>

<style>
  p {
    margin-left: 200px;
  }
  .edit-back {
    margin-left: 200px;
  }
</style>

<body>

    <div class="wrapper">
        <div class="titlebar">
            <a>Business Leaders for Change</a>
        </div>
    </div>

    <div class="wrapper">
        <div class="navBar">
            <div class="navBar-left">
                <ul>
                    <li><a href="<%= new_receipt_path %>" style="text-decoration: none;">Receipts</a></li>
                    <% if $user_role == "Admin" %>
                        <li><a href="<%= receipts_path %>" style="text-decoration: none;">Reimbursement</a></li>
                        <li><a href="<%= expense_types_index_path %>" style="text-decoration: none;">Expense Types</a></li>
                        <li><a class="active" href="<%= members_path %>" style="text-decoration: none;">Officers</a></li>
                        <li><a href="<%= help_index_path%>" style="text-decoration: none;">Help</a></li>
                    <% end %>
                </ul>
            </div>

            <div class="navBar-right">
                <ul>
                <a><%= $user_name %>, <%= $user_role %> &nbsp </a>
                  <div class="signout-link">
                    <%= link_to "Sign Out", destroy_admin_session_path %>
                  </div>
                </ul>
            </div>
        </div>
    </div>

</body>
<% if $user_role == "Admin" %>
    <p id="notice"><%= notice %></p>

    <p>
    <strong>Name:</strong>
    <%= @member.name %>
    </p>

    <p>
    <strong>Email:</strong>
    <%= @member.email %>
    </p>

    <p>
    <strong>Role:</strong>
    <%= @member.role %>
    </p>

    <div class="edit-back">
      <%= link_to 'Edit', edit_member_path(@member) %> |
      <%= link_to 'Back', members_path %>
    </div>

    <body>
      <center>
        <div class="logo">
          <%= image_tag("Untitled_Artwork.png", height: '420', width: '420', :alt => "BLC logo") %>
        </div>
      </center
    </body> 

<% end %>